Repository eclipse-kura/kura, pull requests merged in 2018-12, with the labels that each got.

#2325 Few lint issues fixes
  kura/org.eclipse.kura.broker.artemis.simple.mqtt/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.broker.artemis.simple.mqtt/src/main/java/org/eclipse/kura/broker/artemis/simple/mqtt/ServiceComponent.java
  kura/org.eclipse.kura.core.configuration/src/main/java/org/eclipse/kura/core/configuration/ConfigurationServiceImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/data/store/DbDataStore.java
  kura/org.eclipse.kura.driver.block/src/main/java/org/eclipse/kura/driver/binary/TypeUtil.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/sierra/mc87xx/SierraMc87xxConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/generic/TelitModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/he910/TelitHe910.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/he910/TelitHe910AtCommands.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/he910/TelitHe910ConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/le910/TelitLe910.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/le910v2/TelitLe910v2.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/le910v2/TelitLe910v2AtCommands.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/Firewall/OpenPortsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/Network/TabModemUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/SkinServlet.java
  kura/org.eclipse.kura.xml.marshaller.unmarshaller.provider/src/main/java/org/eclipse/kura/internal/xml/marshaller/unmarshaller/XmlMarshallUnmarshallImpl.java
  kura/test/org.eclipse.kura.core.cloud.test/src/main/java/org/eclipse/kura/core/cloud/CloudPublisherImplTest.java
  kura/test/org.eclipse.kura.core.cloud.test/src/main/java/org/eclipse/kura/core/cloud/CloudServiceTest.java
Labels: enhancement

#2315 Updated Docker README.md
  kura/container/kura/README.md
Labels: documentation

#2327 Changes to fix possible path injection attack in skinServlet.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/SkinServlet.java
Labels: bug

#2335 Added deprecated annotations on old BT APIs
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothAdapter.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothBeaconCommandListener.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothBeaconData.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothBeaconScanListener.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothConnector.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothDevice.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothGatt.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothGattCharacteristic.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothGattSecurityLevel.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothGattService.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothLeNotificationListener.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothLeScanListener.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/BluetoothService.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/listener/AdvertisingReportRecord.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/listener/BluetoothAdvertisementData.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/bluetooth/listener/BluetoothAdvertisementScanListener.java
Labels: kura-bluetooth
