Repository eclipse-kura/kura, pull requests merged in 2019-05, with the labels that each got.

#2404 HostapdManager: use absolute path to pid file instead of relative
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/wifi/HostapdManager.java
Labels: kura-net

#2443 Moved console resources under /admin/
  kura/org.eclipse.kura.web2/OSGI-INF/metatype/org.eclipse.kura.web.Console.xml
  kura/org.eclipse.kura.web2/OSGI-INF/web.xml
  kura/org.eclipse.kura.web2/pom.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/Console.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/OsgiRemoteServiceServlet.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/RedirectServlet.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/SendStatusServlet.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/session/BaseSecurityHandler.java
  kura/org.eclipse.kura.web2/src/main/webapp/WEB-INF/web.xml
  kura/org.eclipse.kura.web2/src/main/webapp/auth.html
  kura/org.eclipse.kura.web2/src/main/webapp/denali.html
  kura/org.eclipse.kura.web2/src/main/webapp/wires_blink.js
  target-platform/org.eclipse.kura.jetty.customizer/src/main/java/org/eclipse/kura/jetty/customizer/KuraJettyCustomizer.java
Labels: enhancement, kura-web2

#2446 Fixed broken snapshot downloading.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/Console.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/ServicesAnchorListItem.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/device/CommandTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/packages/PackagesPanelUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SnapshotsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/util/DownloadHelper.java
Labels: bug

#2445 Solved issue with development environment and empty configuration ret…
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/system/SystemServiceImpl.java
Labels: bug

#2451 Updated csv validation process.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/util/AssetConfigValidator.java
Labels: bug

#2444 Fixed missed command service activation when run in development env.
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.core.cloud/OSGI-INF/commandCloudApp.xml
Labels: bug

#2447 Updated snapshot 0 with latest changes to kura codebase for cloud con…
  kura/distrib/src/main/resources/intel-up2-centos-7-nn/snapshot_0.xml
  kura/distrib/src/main/resources/intel-up2-centos-7/snapshot_0.xml
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/snapshot_0.xml
  kura/distrib/src/main/resources/raspberry-pi-2-nn/snapshot_0.xml
  kura/distrib/src/main/resources/raspberry-pi-2/snapshot_0.xml
  kura/distrib/src/main/resources/rock960-ubuntu-16-nn/snapshot_0.xml
Labels: bug

#2450 Updated documentation for https support.
  _posts/intro/2014-02-01-raspberry-pi-quick-start.md
  _posts/intro/2014-03-01-docker-quick-start.md
  assets/images/admin/untrusted_cert1.png
  assets/images/admin/untrusted_cert2.png
  assets/images/admin/untrusted_cert3.png
Labels: documentation
