Repository eclipse-kura/kura, pull requests merged in 2019-02, with the labels that each got.

#2374 [QA] Updated test dependencies
  kura/org.eclipse.kura.driver.opcua.provider/pom.xml
  kura/test/org.eclipse.kura.internal.driver.opcua.test/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.internal.driver.opcua.test/lib/metrics-core-3.2.2.jar
  kura/test/org.eclipse.kura.internal.driver.opcua.test/lib/sdk-core-0.2.1.jar
  kura/test/org.eclipse.kura.internal.driver.opcua.test/lib/sdk-server-0.2.1.jar
  kura/test/org.eclipse.kura.internal.driver.opcua.test/lib/stack-core-0.2.1.jar
  kura/test/org.eclipse.kura.internal.driver.opcua.test/lib/stack-server-0.2.1.jar
  kura/test/org.eclipse.kura.internal.driver.opcua.test/pom.xml
  target-platform/p2-repo-test-deps/pom.xml
Labels: testing

#2377 Added missing byte array conversion in optimiser library
  kura/org.eclipse.kura.driver.block/src/main/java/org/eclipse/kura/driver/binary/TypeUtil.java
  kura/test/org.eclipse.kura.driver.block.test/src/test/java/org/eclipse/kura/driver/block/test/BlockTaskTest.java
Labels: bug, kura-driver

#2373 Added support for null notification publisher in deploy-v2.
  kura/org.eclipse.kura.core.deployment/src/main/java/org/eclipse/kura/core/deployment/CloudDeploymentHandlerV2.java
Labels: bug, kura-deploy

#2376 Changes to expose simple message creation in corresponding JSON service
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/OSGI-INF/cloud.xml
  kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/src/main/java/org/eclipse/kura/internal/cloudconnection/eclipseiot/mqtt/cloud/CloudConnectionManagerImpl.java
  kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/src/main/java/org/eclipse/kura/internal/cloudconnection/eclipseiot/mqtt/cloud/CloudPayloadJsonDecoder.java
  kura/org.eclipse.kura.core.cloud/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core.cloud/OSGI-INF/cloud.xml
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonEncoder.java
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudPayloadJsonFields.java
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/core/cloud/CloudServiceImpl.java
  kura/org.eclipse.kura.json.marshaller.unmarshaller.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.json.marshaller.unmarshaller.provider/src/main/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/JsonMarshallUnmarshallImpl.java
  kura/org.eclipse.kura.json.marshaller.unmarshaller.provider/src/main/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/message/CloudPayloadJsonDecoder.java
  kura/org.eclipse.kura.json.marshaller.unmarshaller.provider/src/main/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/message/CloudPayloadJsonEncoder.java
  kura/org.eclipse.kura.json.marshaller.unmarshaller.provider/src/main/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/message/CloudPayloadJsonFields.java
  kura/org.eclipse.kura.json.marshaller.unmarshaller.provider/src/main/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/wiregraph/WireGraphJsonMarshallUnmarshallImpl.java
  kura/test/org.eclipse.kura.core.test/pom.xml
  kura/test/org.eclipse.kura.json.marshaller.unmarshaller.provider.test/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.json.marshaller.unmarshaller.provider.test/src/test/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/message/test/CloudPayloadJsonDecoderTest.java
  kura/test/org.eclipse.kura.json.marshaller.unmarshaller.provider.test/src/test/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/message/test/CloudPayloadJsonEncoderTest.java
  kura/test/org.eclipse.kura.json.marshaller.unmarshaller.provider.test/src/test/java/org/eclipse/kura/internal/json/marshaller/unmarshaller/test/JsonEncoderDecoderTest.java
Labels: enhancement

#2381 [QA] Added and updated test dependencies
  kura/test/org.eclipse.kura.internal.driver.opcua.test/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.internal.driver.opcua.test/pom.xml
Labels: testing

#2383 Fixed Asset failure messages not always being shown
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/util/FailureHandler.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtAssetServiceImpl.java
Labels: bug, kura-web2

#2387 CentOS/RPM uninstallation cleanup
  kura/distrib/pom.xml
Labels: enhancement
