Repository eclipse-kura/kura, pull requests merged in 2020-12, with the labels that each got.

#3200 Rollback to previous version due to error inexporting packages in newer releases
  target-platform/config/kura.target-platform.build.properties
Labels: bug

#3201 Updated mirror reference and dependencies versions in jetty.customizer
  target-platform/org.eclipse.kura.jetty.customizer/pom.xml
  target-platform/p2-repo-equinox_3.16.0/pom.xml
Labels: cleanup, enhancement

#3206 Updated Jetty to v.9.4.35.
  kura/distrib/src/main/ant/build_equinox_distrib.xml
  kura/org.eclipse.kura.http.server.manager/META-INF/MANIFEST.MF
  target-platform/config/kura.target-platform.build.properties
  target-platform/org.eclipse.kura.jetty.customizer/pom.xml
  target-platform/p2-repo-equinox_3.16.0/pom.xml
Labels: dependencies, enhancement

#3209 Fixed missing since annotations in new certificate apis.
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/certificate/CertificateInfo.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/certificate/CertificateType.java
Labels: bug

#3213 Enabled GPS for Quectel modems
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/SupportedUsbModemInfo.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/hspa/HspaModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/ex25/QuectelEX25.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/generic/QuectelGenericAtCommands.java
Labels: bug

#3210 Firewall config enhancement
  kura/distrib/config/kura.build.properties
  kura/distrib/src/main/resources/common/kura.service
  kura/distrib/src/main/resources/intel-up2-centos-7/firewall.init
  kura/distrib/src/main/resources/intel-up2-centos-7/iptables.init
  kura/distrib/src/main/resources/intel-up2-centos-7/kuranet.conf
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/firewall.init
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/iptables.init
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/kuranet.conf
  kura/distrib/src/main/resources/raspberry-pi-2/firewall.init
  kura/distrib/src/main/resources/raspberry-pi-2/firewall.service
  kura/distrib/src/main/resources/raspberry-pi-2/iptables.init
  kura/distrib/src/main/resources/raspberry-pi-2/kuranet.conf
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraErrorCode.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/KuraIOException.java
  kura/org.eclipse.kura.linux.net/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.net/pom.xml
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/FilterForwardChainRule.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfig.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/LinuxFirewall.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/LocalRule.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/NatPostroutingChainRule.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/NatPreroutingChainRule.java
  kura/test/org.eclipse.kura.linux.net.test/pom.xml
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/DhcpServerTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/HostapdTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/IPTablesTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/NetworkTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/RoutingAgentTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/WpaSupplicantTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/FilterForwardChainRuleTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/FirewallTestUtils.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/IpTablesConfigTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/LinuxFirewallTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/LocalRuleTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/NatPostroutingChainRuleTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/NatPreroutingChainRuleTest.java
Labels: enhancement, kura-net

#3251 More firewall enahncements
  kura/distrib/src/main/resources/common/kura.service
  kura/distrib/src/main/resources/intel-up2-centos-7/firewall.init
  kura/distrib/src/main/resources/intel-up2-centos-7/iptables.init
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/firewall.init
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/iptables.init
  kura/distrib/src/main/resources/raspberry-pi-2/firewall.init
  kura/distrib/src/main/resources/raspberry-pi-2/iptables.init
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfig.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfigConstants.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/LinuxFirewall.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/FirewallTestUtils.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/IpTablesConfigTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/LinuxFirewallTest.java
Labels: enhancement, kura-net
