Repository eclipse-kura/kura, pull requests merged in 2020-11, with the labels that each got.

#3130 Fixed ssl test making it not position aware.
  kura/test/org.eclipse.kura.core.ssl.test/src/test/java/org/eclipse/kura/core/ssl/SSLSocketFactoryWrapperTest.java
Labels: bug

#3142 Restricted file upload type in Command ui
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/device/CommandTabUi.java
Labels: bug

#3180 Modem classes clean up
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/bg96/QuectelBG96.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/ex25/QuectelEX25.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/zte/me3630/ZteMe3630ConfigGenerator.java
Labels: enhancement, kura-net

#3195 Updated LAUCHER_VERSION in Dockerfile
  kura/container/kura_alpine/Dockerfile
  kura/container/kura_centOS/Dockerfile
Labels: bug

#3141 Add support for multiple cellular modems
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.linux.net/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.net/pom.xml
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/internal/linux/net/modem/GatewayModemDriver.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/NetworkServiceImpl.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/SupportedUsbModems.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/SupportedUsbModemsInfo.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/UsbModemDriver.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/huawei/HuaweiModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/generic/QuectelGeneric.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telefonica/TelefonicaModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/generic/TelitModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/ublox/generic/UbloxModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImpl.java
Labels: enhancement, kura-net

#3184 Kura on a no-root linux user
  kura/distrib/src/main/ant/build_equinox_distrib.xml
  kura/distrib/src/main/deb/control/prerm
  kura/distrib/src/main/resources/common/kura.service
  kura/distrib/src/main/resources/common/manage_kura_users.sh
  kura/distrib/src/main/resources/intel-up2-centos-7-nn/kura_install.sh
  kura/distrib/src/main/resources/intel-up2-centos-7/kura_install.sh
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/kura_install.sh
  kura/distrib/src/main/resources/raspberry-pi-2-nn/kura_install.sh
  kura/distrib/src/main/resources/raspberry-pi-2/kura_install.sh
  kura/distrib/src/main/resources/rock960-ubuntu-16-nn/kura_install.sh
Labels: enhancement
