Repository eclipse-kura/kura, pull requests merged in 2020-08, with the labels that each got.

#3023 Fixed a possible null pointer in getPidsFromTarget.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtComponentServiceImpl.java
Labels: bug

#3029 Fix eddystone-ibeacon docs grammatical errors
  _posts/wires/2018-05-08-1-kura-wires-eddystone.md
  _posts/wires/2018-05-08-kura-wires-ibeacon.md
Labels: documentation

#3030 Fix mqtt-namespace doc grammatical errors
  _posts/ref/2000-01-01-mqtt-namespace.md
Labels: documentation

#3031 Fix driver-asset docs grammatical errors
  _posts/devices/2017-10-11-1-driver-and-assets.md
  _posts/devices/2017-10-11-3-1-asset-implemetation.md
Labels: documentation

#3032 Fix driver docs grammatical errors
  _posts/devices/2018-04-09-1-gpio-driver.md
  _posts/devices/2018-04-09-2-beacon-drivers.md
  _posts/devices/2018-04-09-sensortag-driver.md
Labels: documentation

#3033 Managed exceptions in firewall ports value conversion
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/FirewallPanelUtils.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/OpenPortsTabUi.java
Labels: kura-web2

#3043 Fix directory layout doc grammatical errors
  _posts/admin/2017-05-09-directory-layout.md
Labels: documentation

#3042 Fixes case where a read for all channels fails and reports empty value.
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.asset.cloudlet.provider/src/main/java/org/eclipse/kura/internal/asset/cloudlet/AssetCloudlet.java
Labels: bug

#3034 Clear validation states in reset methods
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/DeviceCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/DeviceCertsTabUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/ServerCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/ServerCertsTabUi.ui.xml
Labels: kura-web2

#3036 Removed some unneeded logging.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.java
Labels: cleanup

#3040 IP forwarding duplicate identification should be now fixed.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/NatTabUi.java
Labels: bug

#3047 Applied cleanup and lint fix in NatTabUi
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/NatTabUi.java
Labels: cleanup

#3048 Modified logging variable to prevent lint issue in FileServlet
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/FileServlet.java
Labels: cleanup
