Repository eclipse-kura/kura, pull requests merged in 2020-01, with the labels that each got.

#2603 Fix #2561 for Wire Publisher and Subscriber
  kura/org.eclipse.kura.wire.component.provider/OSGI-INF/CloudPublisherComponent.xml
  kura/org.eclipse.kura.wire.component.provider/OSGI-INF/CloudSubscriberComponent.xml
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/publisher/CloudPublisher.java
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/subscriber/CloudSubscriber.java
Labels: bug

#2559 Changed ssl protocol code to rely on JVM context if protocol is not s…
  kura/org.eclipse.kura.core/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core/OSGI-INF/metatype/org.eclipse.kura.ssl.SslManagerService.xml
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/ssl/SslManagerServiceImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/ssl/SslManagerServiceOptions.java
Labels: enhancement

#2627 Pid and ExitStatus refactor
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/executor/ExitStatus.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/executor/Pid.java
  kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/util/BluetoothProcess.java
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/CommandCloudApp.java
  kura/org.eclipse.kura.core.deployment/src/main/java/org/eclipse/kura/core/deployment/install/InstallImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/internal/linux/executor/ExecutorUtil.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/executor/LinuxExitStatus.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/executor/LinuxPid.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/executor/LinuxResultHandler.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/executor/privileged/PrivilegedExecutorServiceImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/executor/unprivileged/UnprivilegedExecutorServiceImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/system/SuperSystemService.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/system/SystemAdminServiceImpl.java
  kura/org.eclipse.kura.linux.bluetooth/src/main/java/org/eclipse/kura/linux/bluetooth/util/BluetoothProcess.java
  kura/org.eclipse.kura.linux.bluetooth/src/main/java/org/eclipse/kura/linux/bluetooth/util/BluetoothUtil.java
  kura/org.eclipse.kura.linux.clock/src/main/java/org/eclipse/kura/linux/clock/ClockServiceImpl.java
  kura/org.eclipse.kura.linux.clock/src/main/java/org/eclipse/kura/linux/clock/NtpdClockSyncProvider.java
  kura/org.eclipse.kura.linux.command/src/main/java/org/eclipse/kura/linux/command/CommandServiceImpl.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/DhcpClientManager.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/DhcpServerImpl.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/DhcpServerManager.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dns/LinuxDns.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dns/LinuxDnsServer.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfig.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/LinuxFirewall.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/SupportedUsbModems.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/UsbModemDriver.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/ppp/PppLinux.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/route/RouteServiceImpl.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/EthTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IpAddrShow.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwCapabilityTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwLinkTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwScanTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwconfigLinkTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwlistCapabilityTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwlistScanTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/LinuxNetworkUtil.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/MiiTool.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/wifi/HostapdManager.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/wifi/WifiOptions.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/wifi/WpaSupplicantManager.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/wifi/WpaSupplicantStatus.java
  kura/test/org.eclipse.kura.cloud.test/src/test/java/org/eclipse/kura/cloud/app/command/CommandCloudAppTest.java
  kura/test/org.eclipse.kura.core.deployment.test/src/test/java/org/eclipse/kura/core/deployment/install/InstallImplTest.java
  kura/test/org.eclipse.kura.core.system.test/src/main/java/org/eclipse/kura/core/system/test/SystemServiceTest.java
  kura/test/org.eclipse.kura.core.test/src/test/java/org/eclipse/kura/core/linux/executor/ExecutorServiceImplTest.java
  kura/test/org.eclipse.kura.internal.ble.test/src/test/java/org/eclipse/kura/internal/ble/util/BluetoothProcessTest.java
  kura/test/org.eclipse.kura.linux.clock.test/src/test/java/org/eclipse/kura/linux/clock/ClockServiceImplTest.java
  kura/test/org.eclipse.kura.linux.clock.test/src/test/java/org/eclipse/kura/linux/clock/NtpdClockSyncProviderTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/main/java/org/eclipse/kura/linux/test/net/IPTablesTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImplTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/monitor/WifiMonitorServiceImplTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/visitor/linux/FirewallAutoNatConfigTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/visitor/linux/HostapdConfigTest.java
Labels: enhancement

#2646 Fixed iw command
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/IwCapabilityTool.java
Labels: kura-net
