Repository eclipse-kura/kura, pull requests merged in 2020-04, with the labels that each got.

#2805 Added policies to iptables
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfig.java
Labels: enhancement

#2803 Updated modem reset logic to prevent too fast resets
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/huawei/HuaweiModem.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/eg25/QuectelEG25.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/generic/TelitModem.java
Labels: bug

#2806 Updated connect script to improve modem response.
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/hspa/HspaModemConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/eg25/QuectelEG25ConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/sierra/mc87xx/SierraMc87xxConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/simtech/sim7000/SimTechSim7000ConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/de910/TelitDe910ConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/he910/TelitHe910ConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/telit/le910v2/TelitLe910v2ConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/ublox/generic/UbloxModemConfigGenerator.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/zte/me3630/ZteMe3630ConfigGenerator.java
Labels: enhancement

#2796 Fixed several firewall issues
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/ButtonBar.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/NatTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/OpenPortsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/PortForwardingTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/util/TextFieldValidator.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/GwtFirewallOpenPortEntry.java
Labels: kura-net

#2812 Fixed issue in can service with two can interfaces.
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.protocol.can/src/main/java/org/eclipse/kura/protocol/can/CanConnectionServiceImpl.java
Labels: bug

#2738 Fix container structure
  kura/container/README.md
  kura/container/kura_alpine/Dockerfile
  kura/container/kura_alpine/bin/add-config-ini
  kura/container/kura_alpine/bin/dp-extract-name
  kura/container/kura_alpine/bin/dp-install
  kura/container/kura_alpine/bin/dp-install-local
  kura/container/kura_alpine/bin/dp-register
  kura/container/kura_alpine/bin/kura-entry-point
  kura/container/kura_alpine/bin/pack-kura
  kura/container/kura_alpine/bin/start-kura
  kura/container/kura_alpine/bin/unpack-kura
  kura/container/kura_centOS/Dockerfile
  kura/container/kura_centOS/bin/add-config-ini
  kura/container/kura_centOS/bin/dp-extract-name
  kura/container/kura_centOS/bin/dp-install
  kura/container/kura_centOS/bin/dp-install-local
  kura/container/kura_centOS/bin/dp-register
  kura/container/kura_centOS/bin/kura-entry-point
  kura/container/kura_centOS/bin/pack-kura
  kura/container/kura_centOS/bin/start-kura
  kura/container/kura_centOS/bin/unpack-kura
Labels: enhancement

#2816 Added support for favicon.
  kura/distrib/src/main/ant/build_equinox_distrib.xml
  kura/distrib/src/main/resources/common/favicon/favicon-16x16.png
  kura/distrib/src/main/resources/common/favicon/favicon-32x32.png
  kura/distrib/src/main/resources/common/favicon/favicon-96x96.png
  kura/distrib/src/main/resources/common/favicon/favicon.ico
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/SkinServlet.java
  kura/org.eclipse.kura.web2/src/main/webapp/auth.html
  kura/org.eclipse.kura.web2/src/main/webapp/denali.html
Labels: enhancement

#2819 The sim card not ready case concurs now to modem reset.
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImpl.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImplTest.java
Labels: bug

#2824 Backport of #2822 to release-4.1.0
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.core.comm/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core.comm/pom.xml
  kura/org.eclipse.kura.core.comm/src/main/java/org/eclipse/kura/core/comm/CommConnectionImpl.java
Labels: bug

#2817 Fixed to system tmp the working directory for the execute method.
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/SupportedUsbModems.java
Labels: bug
