Repository eclipse-kura/kura, pull requests merged in 2020-07, with the labels that each got.

#2966 Fixed "Emitters/Receivers" label in UI
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
Labels: cleanup

#2974 Removed icons in confirmation buttons to match the other elements in UI
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/wires/WiresDialogs.ui.xml
Labels: enhancement

#2969 Fixed lint issue with newly contributed ublox modem
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/modem/SupportedUsbModemInfo.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/SupportedUsbModemsFactoryInfo.java
Labels: cleanup

#2968 Applied a patch to identify a corner case where only separators where…
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabTcpIpUi.java
Labels: bug

#2986 Fixed WireGraphService regressions
  kura/org.eclipse.kura.wire.provider/src/main/java/org/eclipse/kura/internal/wire/WireGraphServiceImpl.java
Labels: bug

#2988 Proposal for patching SonarQube rule 4973
  kura/org.eclipse.kura.web2/www
  kura/test/org.eclipse.kura.core.certificates.test/src/test/java/org/eclipse/kura/core/certificates/ExtendedCertificatesManager.java
Labels: enhancement

#2980 Added a check in bg scan thresholds in order to prevent wrong interva…
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
Labels: bug

#2965 Modified modal config in firewall to prevent closing.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/AlertDialog.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/ServicesUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudConnectionsUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudInstancesUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/cloudconnection/CloudInstancesUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/DriversAndAssetsUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/FirewallPanelUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/NatTabUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/OpenPortsTabUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/PortForwardingTabUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/login/LoginUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/NetworkInterfacesTableUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/packages/PackagesPanelUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/CommandUserTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SnapshotsTabUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/settings/SslTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/wires/WiresDialogs.ui.xml
Labels: bug
