Repository eclipse-kura/kura, pull requests merged in 2020-10, with the labels that each got.

#3085 Fixed DNS service using bind9 on Armbian 20.04
  kura/org.eclipse.kura.linux.net/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dns/LinuxDnsServer.java
  kura/org.eclipse.kura.linux.sysv.provider/src/main/java/org/eclipse/kura/internal/linux/sysv/net/dns/LinuxDnsServerSysV.java
Labels: bug

#3091 Backport of dns fix #3085
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.linux.systemd.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.systemd.provider/pom.xml
  kura/org.eclipse.kura.linux.systemd.provider/src/main/java/org/eclipse/kura/internal/linux/systemd/net/dns/DnsServerServiceImpl.java
  kura/org.eclipse.kura.linux.sysv.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.sysv.provider/pom.xml
  kura/org.eclipse.kura.linux.sysv.provider/src/main/java/org/eclipse/kura/internal/linux/sysv/net/dns/DnsServerServiceImpl.java
Labels: bug

#3102 Added RTC device to clock service
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.linux.clock/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.clock/OSGI-INF/metatype/org.eclipse.kura.clock.ClockService.xml
  kura/org.eclipse.kura.linux.clock/pom.xml
  kura/org.eclipse.kura.linux.clock/src/main/java/org/eclipse/kura/linux/clock/ClockServiceImpl.java
Labels: kura-clock

#3105 Added a delay between page restore and reload of the services
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/ServicesUi.java
Labels: bug

#3106 Added a delay between page restore and reload of the services - Backport
  kura/distrib/RELEASE_NOTES.txt
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/ServicesUi.java
Labels: bug

#3110 Fix quectel pdp context config
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/eg25/QuectelEG25ConfigGenerator.java
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
Labels: bug

#3111 Backport fix quectel pdp context config
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/modem/quectel/eg25/QuectelEG25ConfigGenerator.java
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
Labels: bug

#3108 Changed directory check during unzip of compressed files
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/UnZip.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/FileServlet.java
Labels: bug

#3114 Modified iBeacon packet parser
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.ble.ibeacon.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.ble.ibeacon.provider/pom.xml
  kura/org.eclipse.kura.ble.ibeacon.provider/src/main/java/org/eclipse/kura/internal/ble/ibeacon/BluetoothLeIBeaconDecoderImpl.java
  kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/util/BluetoothLeUtil.java
Labels: bug, kura-bluetooth

#3116 Fixed again zip with folders
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/UnZip.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/FileServlet.java
Labels: bug

#3117 Fixed again zip with folders - backport
  kura/org.eclipse.kura.core.cloud/src/main/java/org/eclipse/kura/cloud/app/command/UnZip.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/FileServlet.java
Labels: bug

#3118 Modified iBeacon parser
  kura/org.eclipse.kura.ble.ibeacon.provider/src/main/java/org/eclipse/kura/internal/ble/ibeacon/BluetoothLeIBeaconDecoderImpl.java
  kura/org.eclipse.kura.ble.provider/src/main/java/org/eclipse/kura/internal/ble/util/BluetoothLeUtil.java
Labels: bug, kura-bluetooth

#3124 Fixed CloudPublisher description for the priority field.
  kura/org.eclipse.kura.core.cloud/OSGI-INF/metatype/org.eclipse.kura.cloud.publisher.CloudPublisher.xml
Labels: bug

#3125 Backport fix cloud publisher priority description
  kura/distrib/RELEASE_NOTES.txt
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.core.cloud/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core.cloud/OSGI-INF/metatype/org.eclipse.kura.cloud.publisher.CloudPublisher.xml
  kura/org.eclipse.kura.core.cloud/pom.xml
Labels: bug
