Repository eclipse-kura/kura, pull requests merged in 2021-01, with the labels that each got.

#3256 Fix misc UI issues
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/EntryClassUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/Picker.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/ApplicationCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/CertificateListTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/CertificateListTabUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/CertificateModalListener.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/DeviceCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/HttpsServerCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/HttpsUserCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/ServerCertsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/users/UsersPanelUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/util/FailureHandler.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/OsgiRemoteServiceServlet.java
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
Labels: bug

#3255 Virtual network interfaces management
  kura/distrib/src/main/resources/intel-up2-centos-7-nn/kura.properties
  kura/distrib/src/main/resources/intel-up2-centos-7/kura.properties
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/kura.properties
  kura/distrib/src/main/resources/raspberry-pi-2-nn/kura.properties
  kura/distrib/src/main/resources/raspberry-pi-2/kura.properties
  kura/distrib/src/main/resources/rock960-ubuntu-16-nn/kura.properties
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/system/SystemService.java
  kura/org.eclipse.kura.core/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/system/SystemServiceImpl.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/NetworkServiceImpl.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/util/LinuxNetworkUtil.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkAdminServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkConfigurationServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/visitor/linux/IfcfgConfigReader.java
Labels: enhancement, kura-net

#3264 Added jenkinsfile to the root dir to support multibranch CI
  Jenkinsfile
Labels: enhancement, kura-build

#3266 Fixed unsaved changes dialog for console options
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/security/SecurityPanelUi.java
Labels: bug

#3269 Fix bugs on firewall
  kura/org.eclipse.kura.linux.net/pom.xml
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/IptablesConfig.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/iptables/LinuxFirewall.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/FirewallTestUtils.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/iptables/IpTablesConfigTest.java
Labels: kura-net

#3271 Fixed typo in scriptfilter
  kura/distrib/config/kura.build.properties
  kura/org.eclipse.kura.wire.script.filter.provider/OSGI-INF/metatype/org.eclipse.kura.wire.ScriptFilter.xml
Labels: bug

#3278 Adapt log download feature to journald
  kura/distrib/src/main/resources/intel-up2-centos-7-nn/kura.properties
  kura/distrib/src/main/resources/intel-up2-centos-7/kura.properties
  kura/distrib/src/main/resources/intel-up2-ubuntu-18/kura.properties
  kura/distrib/src/main/resources/raspberry-pi-2-nn/kura.properties
  kura/distrib/src/main/resources/raspberry-pi-2/kura.properties
  kura/distrib/src/main/resources/rock960-ubuntu-16-nn/kura.properties
  kura/org.eclipse.kura.web2/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/LogServlet.java
Labels: enhancement, kura-log

#3279 Aligned Alpine with Centos
  kura/container/kura_alpine/Dockerfile
Labels: bug

#3281 Restored stream close instruction
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/servlet/LogServlet.java
Labels: bug, kura-log, kura-web2
