Repository eclipse-kura/kura, pull requests merged in 2022-01, with the labels that each got.

#3736 Added the jax-rs provider multipart dependency
  kura/distrib/src/main/ant/build_equinox_distrib.xml
  target-platform/config/kura.target-platform.build.properties
  target-platform/p2-repo-common/pom.xml
Labels: enhancement

#3739 Reviewed refresh logic in firewall tabs.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/NatTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/OpenPortsTabUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/firewall/PortForwardingTabUi.java
Labels: bug

#3749 Network configuration clean up
  kura/distrib/src/main/resources/intel-up2-ubuntu-20/snapshot_0.xml
  kura/distrib/src/main/resources/nvidia-jetson-nano/snapshot_0.xml
  kura/distrib/src/main/resources/raspberry-pi-ubuntu-20/snapshot_0.xml
  kura/distrib/src/main/resources/raspberry-pi/snapshot_0.xml
  kura/emulator/org.eclipse.kura.emulator.net/src/main/java/org/eclipse/kura/emulator/net/EmulatedNetworkServiceImpl.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/NetInterfaceState.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/NetworkService.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/dhcp/DhcpServerConfigIP.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/wifi/WifiConfig.java
  kura/org.eclipse.kura.core.net/src/main/java/org/eclipse/kura/core/net/NetworkConfiguration.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/NetworkServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkConfigurationService.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkConfigurationServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/EthernetMonitorServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/WifiMonitorServiceImpl.java
  kura/test/org.eclipse.kura.core.net.test/src/test/java/org/eclipse/kura/core/net/NetworkConfigurationTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/NetworkServiceImplTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/NetworkAdminServiceImplTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/NetworkConfigurationServiceImplTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/visitor/linux/HostapdConfigTest.java
Labels: kura-net

#3754 Update network configuration page
  _posts/config/2017-05-05-network-configuration.md
Labels: documentation
