Repository eclipse-kura/kura, pull requests merged in 2022-11, with the labels that each got.

#4218 fix: Prevent discarding of NetworkConfigurationService properties
  kura/org.eclipse.kura.core.net/src/main/java/org/eclipse/kura/core/net/NetworkConfiguration.java
  kura/org.eclipse.kura.net.admin/OSGI-INF/networkConfigurationService.xml
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkConfigurationServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImpl.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtNetworkServiceImpl.java
  kura/test/org.eclipse.kura.core.net.test/src/test/java/org/eclipse/kura/core/net/NetworkConfigurationTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/NetworkConfigurationServiceImplTest.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/monitor/ModemMonitorServiceImplTest.java
Labels: backport release-5.2.0

#4236 fix(core): Fixed abnormal size of file-based database.
  kura/org.eclipse.kura.core/OSGI-INF/metatype/org.eclipse.kura.core.db.H2DbService.xml
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/db/H2DbServiceImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/db/H2DbServiceOptions.java
  target-platform/p2-repo-equinox_3.16.0/pom.xml
Labels: backport release-5.2.0

#4241 fix: network configuration not updating on Jetson Nano
  kura/distrib/src/main/resources/nvidia-jetson-nano/snapshot_0.xml
Labels: backport release-5.2.0

#4242 fix: Filter out modified.interface.names property
  kura/org.eclipse.kura.core.net/src/main/java/org/eclipse/kura/core/net/NetworkConfiguration.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkConfigurationServiceImpl.java
Labels: backport release-5.2.0

#4247 fix(core.data.store): allow storing null payloads
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/data/store/DbDataStore.java
  kura/test/org.eclipse.kura.core.test/src/test/java/org/eclipse/kura/core/data/store/DbDataStoreStorageTest.java
Labels: backport release-5.2.0

#4253 docs: Added OPC UA subscription documentation
  docs/connect-field-devices/opcua-driver.md
Labels: backport docs-release-5.2

#4252 docs: Added instructions for marketplace certificate import
  docs/administration/application-management.md
Labels: backport docs-release-5.2

#4261 ci: remove deprecated `set-output` command
  .github/workflows/deploy_docs.yml
Labels: backport docs-release-5.2

#4264 ci: bump amannn/action-semantic-pull-request to v5
  .github/workflows/semantic-pr.yml
Labels: backport docs-release-5.2

#4273 docs: Removed max-compact-time parameter.
  docs/core-services/h2db-service.md
Labels: backport docs-release-5.2

#4272 revert: "fix(core): Fixed abnormal size of file-based database. (#4236)"
  kura/org.eclipse.kura.core/OSGI-INF/metatype/org.eclipse.kura.core.db.H2DbService.xml
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/db/H2DbServiceImpl.java
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/db/H2DbServiceOptions.java
  target-platform/p2-repo-equinox_3.16.0/pom.xml
Labels: backport release-5.2.0

#4278 docs(core): Added warning about the database file path to H2DbService metatype
  kura/org.eclipse.kura.core/OSGI-INF/metatype/org.eclipse.kura.core.db.H2DbService.xml
Labels: backport release-5.2.0

#4262 ci: Release Notes automation information improvements
  .github/workflows/release-notes.yml
Labels: backport release-4.1.0, backport release-5.2.0

#4276 docs: Added warning about H2 database parent directory permissions
  docs/core-services/h2db-service.md
Labels: backport docs-release-5.2
