Repository eclipse-kura/kura, pull requests merged in 2023-05, with the labels that each got.

#4629 fix: Disabled dhcpcd service for generic platform.
  kura/distrib/src/main/resources/generic-aarch64/kura_install.sh
  kura/distrib/src/main/resources/generic-arm32/kura_install.sh
  kura/distrib/src/main/resources/generic-x86_64/kura_install.sh
Labels: backport release-5.3.0

#4630 fix(distrib): add named.rfc file to apparmor exceptions
  kura/distrib/src/main/resources/common/named/usr.sbin.named
Labels: backport release-5.3.0

#4638 fix(web2): GPS modem config is done independently of set IP status
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/net2/configuration/NetworkConfigurationServicePropertiesBuilder.java
Labels: backport release-5.3.0

#4633 fix(nm): use UNMANAGED location source
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
Labels: backport release-5.3.0

#4643 fix(distrib): aligned disabled services on all kura-network installers
  kura/distrib/src/main/resources/intel-up2-ubuntu-20/kura_install.sh
  kura/distrib/src/main/resources/nvidia-jetson-nano/kura_install.sh
  kura/distrib/src/main/resources/raspberry-pi-arm64/kura_install.sh
  kura/distrib/src/main/resources/raspberry-pi-armhf/kura_install.sh
Labels: backport release-5.3.0

#4637 fix: Do not remove interface address while dhclient is running
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/NetworkAdminServiceImpl.java
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/NetworkAdminServiceImplTest.java
Labels: backport release-5.3.0

#4649 docs: add info about AP scanning known issue
  docs/gateway-configuration/wifi-configuration.md
Labels: backport docs-release-5.3

#4635 fix(web2): Added missing wifi password content check.
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/net/GwtNetworkServiceImpl.java
Labels: backport release-5.3.0

#4655 fix(web2): DHCP renew button is now disabled except in WAN/LAN mode using dhcp
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabTcpIpUi.java
Labels: backport release-5.3.0

#4665 fix(web2): save configured wifi channel in GWT interface
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/net2/configuration/GwtNetInterfaceConfigBuilder.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/net2/status/NetworkStatusServiceAdapter.java
Labels: backport release-5.3.0

#4652 fix: wan priority description defaults.
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages_ja.properties
Labels: backport release-5.3.0

#4662 fix: Improved the way netplan is disabled on Kura install
  kura/distrib/src/main/resources/generic-aarch64/deb/control/prerm
  kura/distrib/src/main/resources/generic-aarch64/kura_install.sh
  kura/distrib/src/main/resources/generic-arm32/deb/control/prerm
  kura/distrib/src/main/resources/generic-arm32/kura_install.sh
  kura/distrib/src/main/resources/generic-x86_64/deb/control/prerm
  kura/distrib/src/main/resources/generic-x86_64/kura_install.sh
Labels: backport release-5.3.0

#4670 fix(nm): actually delete connection upon device disconnection
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
Labels: backport release-5.3.0

#4673 fix: porting of fixes for the dns management
  kura/distrib/src/main/ant/build_equinox_distrib.xml
  kura/distrib/src/main/resources/common/kura-dhclient-enter-hook
  kura/distrib/src/main/resources/intel-up2-ubuntu-20/kura_install.sh
  kura/distrib/src/main/resources/nvidia-jetson-nano/kura_install.sh
  kura/distrib/src/main/resources/raspberry-pi-arm64/kura_install.sh
  kura/distrib/src/main/resources/raspberry-pi-armhf/kura_install.sh
  kura/org.eclipse.kura.linux.net/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/DhcpClientManager.java
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dns/LinuxDns.java
  kura/org.eclipse.kura.net.admin/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/monitor/DnsMonitorServiceImpl.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/visitor/linux/DhcpClientConfigWriter.java
  kura/org.eclipse.kura.net.admin/src/main/java/org/eclipse/kura/net/admin/visitor/linux/LinuxWriteVisitor.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/dns/LinuxDnsTest.java
  kura/test/org.eclipse.kura.net.admin.test/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.net.admin.test/src/test/java/org/eclipse/kura/net/admin/monitor/DnsMonitorServiceImplTest.java
Labels: backport release-5.3.0

#4674 fix: Prevented ifup-local from writing duplicate DNS entries
  kura/distrib/src/main/resources/common/ifup-local.debian
  kura/distrib/src/main/resources/common/ifup-local.raspbian
Labels: backport release-5.3.0

#4671 test(linux.net.dhcp.server): added `DnsmasqToolTest` and `DhcpdToolTest`
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/server/DnsmasqTool.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/dhcp/server/DhcpdToolTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/java/org/eclipse/kura/linux/net/dhcp/server/DnsmasqToolTest.java
  kura/test/org.eclipse.kura.linux.net.test/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: backport release-5.3.0

#4675 docs: Updated Network page with Not Managed interfaces notes
  docs/gateway-configuration/network-configuration.md
Labels: backport docs-release-5.3

#4676 fix: Wrong PKCS11KeystoreServiceImpl bind methods
  kura/org.eclipse.kura.core.keystore/OSGI-INF/org.eclipse.kura.core.keystore.pkcs11KeystoreService.xml
Labels: backport release-5.3.0

#4684 fix: Updated named apparmor profile to include /usr/share/dns
  kura/distrib/src/main/resources/common/named/usr.sbin.named
Labels: backport release-5.3.0

#4685 fix: Removed deprecated named options
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dns/LinuxDnsServer.java
Labels: backport release-5.3.0

#4688 fix(nm): Added convertion between interfaceId and interfaceName in firewall co…
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/configuration/NMConfigurationServiceImpl.java
Labels: backport release-5.3.0

#4690 fix(core.deployment): dpa.properties is written even if package is already in persistence
  kura/org.eclipse.kura.core.deployment/src/main/java/org/eclipse/kura/core/deployment/download/DownloadFileUtilities.java
  kura/org.eclipse.kura.core.deployment/src/main/java/org/eclipse/kura/core/deployment/download/impl/DownloadImpl.java
  kura/org.eclipse.kura.core.deployment/src/main/java/org/eclipse/kura/core/deployment/install/InstallImpl.java
  kura/org.eclipse.kura.core.deployment/src/main/java/org/eclipse/kura/core/deployment/util/FileUtilities.java
  kura/org.eclipse.kura.deployment.agent/src/main/java/org/eclipse/kura/deployment/agent/impl/DeploymentAgent.java
  kura/test/org.eclipse.kura.core.deployment.test/src/test/java/org/eclipse/kura/core/deployment/install/InstallImplTest.java
Labels: backport release-5.3.0

#4693 docs: Improved description of DEPLOY-V2 reboot metrics
  docs/references/mqtt-namespace.md
Labels: backport docs-release-5.2, backport docs-release-5.3
