Repository eclipse-kura/kura, pull requests merged in 2023-06, with the labels that each got.

#4702 docs(mqtt-namespace): add Container Image API documentation to mqtt-namespace
  docs/references/mqtt-namespace.md
Labels: backport docs-release-5.2, backport docs-release-5.3

#4709 fix: rest wire provider minor version bugfix
  kura/distrib/pom.xml
Labels: backport release-5.2.0, backport release-5.3.0

#4721 build: Updated org.xerial:sqlite-jdbc to 3.42.0.0
  NOTICE.md
  target-platform/config/kura.target-platform.build.properties
Labels: backport release-5.3.0

#4725 fix: Fixed error on SQLite dp reinstallation
  kura/org.eclipse.kura.db.sqlite.provider/src/main/java/org/eclipse/kura/internal/db/sqlite/provider/SqliteProviderActivator.java
  kura/test/org.eclipse.kura.db.sqlite.provider.test/src/test/java/org/eclipse/kura/internal/db/sqlite/provider/SqliteProviderActivatorTest.java
Labels: backport release-5.3.0

#4728 docs: Added note about Rasbpberry Pi OS 32bit with aarch64 kernel
  docs/core-services/sqlite-db-service.md
  docs/getting-started/raspberry-pi-raspberryos-quick-start.md
Labels: backport docs-release-5.3

#4734 fix: added correct permissions to docker file
  kura/distrib/src/main/resources/docker-alpine-x86_64-nn/Dockerfile
  kura/distrib/src/main/resources/docker-ubi8-x86_64-nn/Dockerfile
Labels: backport release-5.3.0

#4736 fix: Fixed asset scale and offset not being applied in listen mode
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseAsset.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/DriverState.java
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/asset/WireAsset.java
  kura/test/org.eclipse.kura.wire.component.provider.test/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/MockDriver.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/OnChangeCacheTest.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/ScaleOffsetTest.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/WireAssetTestBase.java
Labels: backport release-5.3.0

#4747 docs: Removed new relase announcement banner
  overrides/main.html
Labels: backport docs-release-5.2, backport docs-release-5.3
