Repository eclipse-kura/kura, pull requests merged in 2024-10, with the labels that each got.

#5385 fix: Updated the Eclipse Marketplace certificate
  kura/distrib/src/main/resources/common/cacerts.ks
Labels: backport release-5.6.0

#5387 ci: fix Github actions permissions for documentation branches
  .github/workflows/backport.yml
  .github/workflows/deploy_docs.yml
Labels: backport docs-release-5.5, backport docs-release-5.6

#5388 docs: remove obsolete links
  mkdocs.yml
Labels: backport docs-release-5.6

#5386 ci: fix Github actions permissions
  .github/workflows/backport.yml
  .github/workflows/release-notes.yml
  .github/workflows/stale-issues.yml
  .github/workflows/version-uptick.yml
Labels: backport release-5.5.0, backport release-5.6.0

#5378 feat(linux.net): Modified dhcp server selection order
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/DhcpServerManager.java
Labels: backport release-5.6.0

#5398 ci: use newly introduced bot personal access token for github workflows
  .github/workflows/backport.yml
Labels: backport docs-release-5.6

#5397 ci: use newly introduced bot personal access token for github workflows
  .github/workflows/backport.yml
  .github/workflows/release-notes.yml
  .github/workflows/version-uptick.yml
Labels: backport docs-release-5.5, backport docs-release-5.6

#5381 feat(api): added gnss type data to PositionService
  kura/emulator/org.eclipse.kura.emulator.position/META-INF/MANIFEST.MF
  kura/emulator/org.eclipse.kura.emulator.position/src/main/java/org/eclipse/kura/emulator/position/PositionServiceImpl.java
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/position/GNSSType.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/position/PositionService.java
  kura/org.eclipse.kura.linux.position/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/GpsDevice.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/GpsdPositionProvider.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/NMEAParser.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionProvider.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionServiceImpl.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/SerialDevicePositionProvider.java
  kura/org.eclipse.kura.rest.position.provider/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/PositionServiceTest.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/UseGpsdPositionProviderTest.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/resources/gpsd-raw-json-device-2-2.txt
  kura/test/org.eclipse.kura.rest.position.provider.test/META-INF/MANIFEST.MF
Labels: backport release-5.6.0

#5411 fix(position): added missing and fixed wrong copyrights in updated position API
  kura/emulator/org.eclipse.kura.emulator.position/src/main/java/org/eclipse/kura/emulator/position/PositionServiceImpl.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/position/GNSSType.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/position/PositionService.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/GpsDevice.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/GpsdPositionProvider.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/NMEAParser.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionProvider.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionServiceImpl.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/SerialDevicePositionProvider.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/PositionServiceTest.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/UseGpsdPositionProviderTest.java
Labels: backport release-5.6.0

#5384 feat: Added asset name in error logs
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseAsset.java
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/asset/WireAsset.java
Labels: backport release-5.6.0

#5406 feat(nm): add managed GPS mode
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/KuraModemGPSMode.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/ModemManagerDbusWrapper.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
Labels: backport release-5.6.0

#5414 feat(api): add getSupportedGpsModes() to modem status API
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/modem/ModemGpsMode.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/modem/ModemInterfaceStatus.java
  kura/org.eclipse.kura.nm/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
  kura/org.eclipse.kura.rest.network.status.provider/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
Labels: backport release-5.6.0

#5377 docs(connect-field-devices): Added scaleoffset.type and rewritten scale and offset
  docs/connect-field-devices/asset-implemetation.md
Labels: backport docs-release-5.6

#5420 feat: Improve container service description
  kura/org.eclipse.kura.container.orchestration.provider/OSGI-INF/metatype/org.eclipse.kura.container.orchestration.provider.ContainerOrchestrationService.xml
Labels: backport release-5.6.0

#5418 feat(asset.provider): Added type for Scale and Offset in Channels
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/channel/Channel.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/channel/ScaleOffsetType.java
  kura/org.eclipse.kura.asset.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/AssetConstants.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseAsset.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseChannelDescriptor.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/internal/asset/provider/BaseAssetConfiguration.java
  kura/org.eclipse.kura.web2/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.wire.component.provider/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.asset.provider.test/src/main/java/org/eclipse/kura/asset/provider/test/AssetTest.java
  kura/test/org.eclipse.kura.rest.wire.provider.test/src/main/java/org/eclipse/kura/rest/wire/provider/test/Snippets.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/ScaleOffsetTest.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/WireAssetTestBase.java
Labels: backport release-5.6.0

#5408 docs: add newly introduced GPS mode property
  docs/gateway-configuration/network-configuration.md
Labels: backport docs-release-5.6

#5432 feat(asset.provider): Now the DataType sent to the driver depends on the DataType of the channel and theDataType of the scaleOffsetDataType field and a new ScaleOffsetDataType, LONG, has been added
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/channel/ChannelRecord.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/channel/ScaleOffsetType.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/asset/provider/BaseAsset.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/internal/asset/provider/BaseAssetConfiguration.java
  kura/org.eclipse.kura.asset.provider/src/main/java/org/eclipse/kura/internal/asset/provider/helper/ChannelRecordHelper.java
  kura/test/org.eclipse.kura.asset.provider.test/src/main/java/org/eclipse/kura/asset/provider/helper/test/ChannelRecordHelperTest.java
  kura/test/org.eclipse.kura.asset.provider.test/src/main/java/org/eclipse/kura/asset/provider/test/AssetTest.java
  kura/test/org.eclipse.kura.rest.wire.provider.test/src/main/java/org/eclipse/kura/rest/wire/provider/test/Snippets.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/ScaleOffsetTest.java
Labels: backport release-5.6.0

#5433 docs: Added updates according with #5432
  docs/connect-field-devices/asset-implemetation.md
Labels: backport docs-release-5.6

#5431 build: Protobuf update to 3.25.5
  kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/pom.xml
  kura/org.eclipse.kura.cloudconnection.kapua.mqtt.provider/pom.xml
  kura/org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider/pom.xml
  kura/test/org.eclipse.kura.cloudconnection.kapua.mqtt.provider.test/pom.xml
  kura/test/org.eclipse.kura.core.cloud.command.test/pom.xml
  target-platform/config/kura.target-platform.build.properties
Labels: backport release-5.6.0

#5443 docs: remove duplicated paragraph
  docs/java-application-development/configurable-application.md
Labels: backport docs-release-5.5, backport docs-release-5.6

#5434 feat(position): added datetime and gnsstype to position service static provider
  kura/org.eclipse.kura.linux.position/OSGI-INF/metatype/org.eclipse.kura.position.PositionService.xml
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionServiceImpl.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionServiceOptions.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/PositionServiceTest.java
Labels: backport release-5.6.0

#5419 feat(distrib): Network configuration customization during Kura install
  kura/distrib/src/main/ant/build_equinox_distrib.xml
  kura/distrib/src/main/resources/common/comment_interfaces_file.py
  kura/distrib/src/main/resources/common/customize-installation.sh
  kura/distrib/src/main/resources/common/customize_iptables.py
  kura/distrib/src/main/resources/common/customize_kura_properties.py
  kura/distrib/src/main/resources/common/customize_snapshot.py
  kura/distrib/src/main/resources/common/iptables/iptables
  kura/distrib/src/main/resources/common/iptables/iptables-raspberry
  kura/distrib/src/main/resources/common/network_tools.py
  kura/distrib/src/main/resources/common/snapshots/snapshot_0.xml
  kura/distrib/src/main/resources/common/snapshots/snapshot_0.xml-generic-device
  kura/distrib/src/main/resources/common/snapshots/template_firewall_eth
  kura/distrib/src/main/resources/common/snapshots/template_firewall_eth_wlan
  kura/distrib/src/main/resources/common/snapshots/template_multiple_eth_no_wlan
  kura/distrib/src/main/resources/common/snapshots/template_multiple_eth_one_wlan
  kura/distrib/src/main/resources/common/snapshots/template_one_eth_no_wlan
  kura/distrib/src/main/resources/common/snapshots/template_one_eth_one_wlan
  kura/distrib/src/main/resources/generic-aarch64-nn/deb/control/control
  kura/distrib/src/main/resources/generic-aarch64-nn/deb/control/postinst
  kura/distrib/src/main/resources/generic-aarch64-nn/kura_install.sh
  kura/distrib/src/main/resources/generic-aarch64/deb/control/control
  kura/distrib/src/main/resources/generic-aarch64/deb/control/postinst
  kura/distrib/src/main/resources/generic-aarch64/kura_install.sh
  kura/distrib/src/main/resources/generic-arm32-nn/deb/control/control
  kura/distrib/src/main/resources/generic-arm32-nn/deb/control/postinst
  kura/distrib/src/main/resources/generic-arm32-nn/kura_install.sh
  kura/distrib/src/main/resources/generic-arm32/deb/control/control
  kura/distrib/src/main/resources/generic-arm32/deb/control/postinst
  kura/distrib/src/main/resources/generic-arm32/kura_install.sh
  kura/distrib/src/main/resources/generic-x86_64-nn/deb/control/control
  kura/distrib/src/main/resources/generic-x86_64-nn/deb/control/postinst
  kura/distrib/src/main/resources/generic-x86_64-nn/kura_install.sh
  kura/distrib/src/main/resources/generic-x86_64/deb/control/control
  kura/distrib/src/main/resources/generic-x86_64/deb/control/postinst
  kura/distrib/src/main/resources/generic-x86_64/kura_install.sh
Labels: backport release-5.6.0

#5454 docs: Updated getting started page with initial network/firewall config
  docs/getting-started/install-kura.md
Labels: backport docs-release-5.6

#5457 docs: Fixed small formatting issues
  docs/getting-started/install-kura.md
Labels: backport docs-release-5.6

#5452 feat: Added new KeystoreService.getKeyManagers() method that allows provider selection
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/security/keystore/KeystoreService.java
  kura/org.eclipse.kura.core.keystore/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core.keystore/src/main/java/org/eclipse/kura/core/keystore/BaseKeystoreService.java
  kura/org.eclipse.kura.rest.keystore.provider/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.core.keystore.test/src/test/java/org/eclipse/kura/core/keystore/FilesystemKeystoreServiceImplTest.java
  kura/test/org.eclipse.kura.core.testutil/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.core.testutil/src/main/java/org/eclipse/kura/core/testutil/pki/TestCA.java
Labels: backport release-5.6.0

#5456 refactor(position): updated name of position service api
  kura/emulator/org.eclipse.kura.emulator.position/src/main/java/org/eclipse/kura/emulator/position/PositionServiceImpl.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/position/PositionService.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/GpsDevice.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/GpsdPositionProvider.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/NMEAParser.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionProvider.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionServiceImpl.java
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/SerialDevicePositionProvider.java
  kura/org.eclipse.kura.rest.position.provider/src/main/java/org/eclipse/kura/internal/rest/position/PositionRestService.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/PositionServiceTest.java
  kura/test/org.eclipse.kura.linux.position.test/src/test/java/org/eclipse/kura/linux/position/UseGpsdPositionProviderTest.java
  kura/test/org.eclipse.kura.rest.position.provider.test/src/main/java/org/eclipse/kura/rest/position/provider/test/PositionRestServiceTest.java
Labels: backport release-5.6.0

#5462 build: Reduce number of job history to 5
  Jenkinsfile
Labels: backport release-5.0.0, backport release-5.1.0, backport release-5.2.0, backport release-5.3.0, backport release-5.4.0, backport release-5.5.0, backport release-5.6.0

#5472 fix(linux.position): wrong option name in metatype
  kura/org.eclipse.kura.linux.position/OSGI-INF/metatype/org.eclipse.kura.position.PositionService.xml
Labels: backport release-5.6.0

#5481 feat(nm): Added SIM operator ID to Network Status
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/modem/Sim.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
  kura/org.eclipse.kura.rest.network.status.provider/src/main/java/org/eclipse/kura/network/status/provider/api/SimDTO.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/status/NMStatusConverterTest.java
  kura/test/org.eclipse.kura.rest.network.status.provider.test/src/main/java/org/eclipse/kura/rest/network/status/provider/test/NetworkStatusRestServiceImplTest.java
Labels: backport release-5.6.0

#5482 docs: Added operatorID NetworkStatus REST page
  docs/core-services/network-status-rest-v1.md
Labels: backport docs-release-5.6

#5463 chore(poms): uptick version of properties maven plugin
  kura/distrib/pom.xml
  kura/org.eclipse.kura.container.orchestration.provider/pom.xml
  kura/pom.xml
  target-platform/p2-repo-common/pom.xml
  target-platform/pom.xml
Labels: backport release-5.6.0

#5485 fix(nm): Fixed SupportedCapabilities in Modem status
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/modem/ModemInterfaceStatus.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/NMDbusConnectorTest.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/status/NMStatusConverterTest.java
  kura/test/org.eclipse.kura.rest.network.status.provider.test/src/main/java/org/eclipse/kura/rest/network/status/provider/test/NetworkStatusRestServiceImplTest.java
Labels: backport release-5.6.0

#5487 fix: Container page refresh performed at completed operation
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/device/DockerContainersTabUi.java
Labels: backport release-5.6.0

#5479 feat: Added support for emitting connection errors in WireAsset
  kura/org.eclipse.kura.wire.component.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/asset/WireAsset.java
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/asset/WireAssetConstants.java
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/asset/WireAssetOCD.java
  kura/org.eclipse.kura.wire.component.provider/src/main/java/org/eclipse/kura/internal/wire/asset/WireAssetOptions.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/AssetErrorTest.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/MockDriver.java
  kura/test/org.eclipse.kura.wire.component.provider.test/src/main/java/org/eclipse/kura/internal/wire/asset/test/WireAssetTestBase.java
Labels: backport release-5.6.0

#5495 fix: Java 11+ PKCS11 provider setup
  kura/org.eclipse.kura.core.keystore/src/main/java/org/eclipse/kura/core/keystore/PKCS11KeystoreServiceImpl.java
Labels: backport release-5.6.0

#5480 docs: Documented emitting connection errors in WireAsset
  docs/kura-wires/assets-as-wire-components.md
Labels: backport docs-release-5.6

#5496 feat(web-ui): Added a column filter to channels table in the asset configuration
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/drivers/assets/AssetConfigurationUi.ui.xml
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/AssetConstants.java
  kura/org.eclipse.kura.web2/src/main/resources/org/eclipse/kura/web/client/messages/Messages.properties
Labels: backport release-5.6.0

#5493 build: updated jetty version to 9.4.55.v20240627
  target-platform/config/kura.target-platform.build.properties
  target-platform/org.eclipse.kura.jetty.customizer/pom.xml
Labels: backport release-5.6.0

#5490 fix: Improvement on Raw cloud connection
  kura/org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider/OSGI-INF/cloud.xml
  kura/org.eclipse.kura.cloudconnection.raw.mqtt.provider/OSGI-INF/cloud.xml
  kura/org.eclipse.kura.cloudconnection.raw.mqtt.provider/src/main/java/org/eclipse/kura/cloudconnection/raw/mqtt/cloud/RawMqttCloudEndpoint.java
Labels: backport release-5.6.0
