Repository eclipse-kura/kura, pull requests merged in 2024-11, with the labels that each got.

#5491 fix(nm): AP scan not reports correct Wifi Security
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/wifi/WifiAccessPoint.java
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/net/status/wifi/WifiFlag.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/enums/NM80211ApFlags.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/status/NMStatusConverter.java
  kura/org.eclipse.kura.rest.network.status.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.rest.network.status.provider/src/main/java/org/eclipse/kura/network/status/provider/api/WifiAccessPointDTO.java
  kura/org.eclipse.kura.web2/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/net2/status/NetworkStatusServiceAdapter.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/shared/model/GwtWifiSecurity.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/enums/NM80211ApFlagsTest.java
  kura/test/org.eclipse.kura.rest.network.status.provider.test/src/main/java/org/eclipse/kura/rest/network/status/provider/test/NetworkStatusRestServiceImplTest.java
Labels: backport release-5.6.0

#5499 feat: Add default log manager property
  kura/distrib/src/main/resources/docker-x86_64-nn/kura.properties
  kura/distrib/src/main/resources/generic-aarch64-nn/kura.properties
  kura/distrib/src/main/resources/generic-aarch64/kura.properties
  kura/distrib/src/main/resources/generic-arm32-nn/kura.properties
  kura/distrib/src/main/resources/generic-arm32/kura.properties
  kura/distrib/src/main/resources/generic-x86_64-nn/kura.properties
  kura/distrib/src/main/resources/generic-x86_64/kura.properties
  kura/org.eclipse.kura.api/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/system/SystemService.java
  kura/org.eclipse.kura.core.system/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.core.system/src/main/java/org/eclipse/kura/core/system/SystemServiceImpl.java
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/server/GwtLogServiceImpl.java
  kura/test/org.eclipse.kura.core.system.test/src/main/java/org/eclipse/kura/core/system/test/SystemServiceTest.java
Labels: backport release-5.6.0

#5509 fix: Linux.Pid equals override
  kura/org.eclipse.kura.core/src/main/java/org/eclipse/kura/core/linux/executor/LinuxPid.java
Labels: backport release-5.6.0

#5500 docs: Added a note about the new LogManager property in Device page
  docs/gateway-configuration/device-information.md
Labels: backport docs-release-5.6

#5492 docs: Updated network status rest page
  docs/core-services/network-status-rest-v1.md
Labels: backport docs-release-5.6

#5523 fix: Update kura.setup for oomph to new repo
  kura/setups/kura.setup
Labels: backport release-5.6.0

#5524 build(deps): updated Jetty 9.4.55 -> 9.4.56
  NOTICE.md
  target-platform/config/kura.target-platform.build.properties
  target-platform/org.eclipse.kura.jetty.customizer/pom.xml
Labels: backport release-5.6.0

#5522 fix(distrib): Updated installer script to write all interface names to snapshot file
  kura/distrib/src/main/resources/common/customize_snapshot.py
Labels: backport release-5.6.0

#5532 fix: Ignore modem state when getting position from MM
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/NMDbusConnector.java
Labels: backport release-5.6.0

#5535 fix(rest.network.configuration): Fix net interfaces property management again
  kura/org.eclipse.kura.rest.network.configuration.provider/META-INF/MANIFEST.MF
  kura/org.eclipse.kura.rest.network.configuration.provider/src/main/java/org/eclipse/kura/internal/rest/network/configuration/NetworkConfigurationRestService.java
  kura/test/org.eclipse.kura.rest.network.configuration.provider.test/META-INF/MANIFEST.MF
  kura/test/org.eclipse.kura.rest.network.configuration.provider.test/src/main/java/org/eclipse/kura/rest/network/configuration/provider/test/NetworkConfigurationRestServiceTest.java
  kura/test/org.eclipse.kura.rest.network.configuration.provider.test/src/main/java/org/eclipse/kura/rest/network/configuration/provider/test/responses/RestNetworkConfigurationJson.java
Labels: backport release-5.6.0

#5533 fix(distrib): revert #5522
  kura/distrib/src/main/resources/common/customize_snapshot.py
Labels: backport release-5.6.0

#5540 docs: Improve container instance metatype descriptions
  kura/org.eclipse.kura.container.provider/OSGI-INF/metatype/org.eclipse.kura.container.provider.ContainerInstance.xml
Labels: backport release-5.6.0

#5529 fix: Use dynamic policy for PositionProvider reference in PositionService
  kura/org.eclipse.kura.linux.position/OSGI-INF/position.xml
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/PositionServiceImpl.java
Labels: backport release-5.6.0

#5547 docs: Added a note regarding Debian packages in Device tab
  docs/gateway-configuration/device-information.md
Labels: backport docs-release-5.6

#5550 fix: Clash in dnsmasq lease file configuration option
  kura/org.eclipse.kura.linux.net/src/main/java/org/eclipse/kura/linux/net/dhcp/server/DnsmasqTool.java
Labels: backport release-5.6.0

#5551 fix(web2): Fixed MTU field visualization
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabAdvancedUi.java
Labels: backport release-5.6.0

#5554 fix: Corrected the checks for empty subnet and gateway
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabIp4Ui.java
Labels: backport release-5.6.0

#5557 fix: ipv4 empty subnet gateway checks - improvement
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabIp4Ui.java
Labels: backport release-5.6.0

#5564 chore: Cleanup of app update log
  kura/org.eclipse.kura.cloudconnection.kapua.mqtt.provider/src/main/java/org/eclipse/kura/core/cloud/CloudServiceImpl.java
Labels: backport release-5.6.0

#5565 fix: position not updated when fix is lost
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMLocationParser.java
  kura/org.eclipse.kura.nm/src/main/java/org/eclipse/kura/nm/position/MMPositionProvider.java
  kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/position/MMPositionProviderTest.java
  kura/test/org.eclipse.kura.nm.test/src/test/resources/noFixNmeaSentences.txt
Labels: backport release-5.6.0

#5555 docs: Documented raw MQTT cloud connection
  docs/cloud-platform/raw-cloud-connection.md
  mkdocs.yml
Labels: backport docs-release-5.6

#5573 fix: Improved ordering of services list
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/EntryClassUi.java
Labels: backport release-5.6.0

#5572 fix: fixed loading of country code
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.java
Labels: backport release-5.6.0

#5574 fix: Fixed IPv6 validation
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabIp6Ui.java
Labels: backport release-5.6.0

#5585 fix: correctly stopping gpsd thread
  kura/org.eclipse.kura.linux.position/src/main/java/org/eclipse/kura/linux/position/gpsd/GpsdPositionProvider.java
Labels: backport release-5.6.0

#5583 fix(web2): Fixed wireless mode selection
  kura/org.eclipse.kura.web2/src/main/java/org/eclipse/kura/web/client/ui/network/TabWirelessUi.java
Labels: backport release-5.6.0

#5591 docs: Align bundle states description
  docs/references/rest-apis/rest-inventory-api.md
Labels: backport docs-release-5.4, backport docs-release-5.5, backport docs-release-5.6

#5592 docs: Report type values for SystemResources
  docs/references/rest-apis/rest-inventory-api.md
Labels: backport docs-release-5.4, backport docs-release-5.5, backport docs-release-5.6
